-- MySQL Script generated by MySQL Workbench
-- sob, 4 sty 2020, 14:58:30
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema joomla
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema joomla
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `joomla` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`#__crc_files`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`#__crc_files` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `path` TEXT NOT NULL,
  `filename` VARCHAR(512) NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `joomla`.`#__users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `joomla`.`#__users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(400) NOT NULL DEFAULT '',
  `username` VARCHAR(150) NOT NULL DEFAULT '',
  `email` VARCHAR(100) NOT NULL DEFAULT '',
  `password` VARCHAR(100) NOT NULL DEFAULT '',
  `block` TINYINT(4) NOT NULL DEFAULT '0',
  `sendEmail` TINYINT(4) NULL DEFAULT '0',
  `registerDate` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `lastvisitDate` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `activation` VARCHAR(100) NOT NULL DEFAULT '',
  `params` TEXT NOT NULL,
  `lastResetTime` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'Date of last password reset',
  `resetCount` INT(11) NOT NULL DEFAULT '0' COMMENT 'Count of password resets since lastResetTime',
  `otpKey` VARCHAR(1000) NOT NULL DEFAULT '' COMMENT 'Two factor authentication encrypted keys',
  `otep` VARCHAR(1000) NOT NULL DEFAULT '' COMMENT 'One time emergency passwords',
  `requireReset` TINYINT(4) NOT NULL DEFAULT '0' COMMENT 'Require user to reset password on next login',
  PRIMARY KEY (`id`),
  INDEX `idx_name` (`name`(100) ASC) VISIBLE,
  INDEX `idx_block` (`block` ASC) VISIBLE,
  INDEX `username` (`username` ASC) VISIBLE,
  INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 874
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`#__crc_check_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`#__crc_check_history` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `users_id` INT(11) NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_crc_check_history_users_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_crc_check_history_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `joomla`.`#__users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`#__crc_check`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`#__crc_check` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `crc` VARCHAR(32) NOT NULL,
  `veryfied` TINYINT NOT NULL DEFAULT 0,
  `checked_out` INT(10) NOT NULL DEFAULT 0,
  `checked_out_time` DATETIME NOT NULL DEFAULT 0000-00-00 00:00:00,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `crc_files_id` BIGINT UNSIGNED NOT NULL,
  `checked_out_time` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `checked_out_time`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_crc_check_crc_files_idx` (`crc_files_id` ASC) VISIBLE,
  INDEX `fk_crc_check_crc_check_history_idx` (`checked_out_time` ASC) VISIBLE,
  CONSTRAINT `fk_crc_check_crc_files`
    FOREIGN KEY (`crc_files_id`)
    REFERENCES `mydb`.`#__crc_files` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_crc_check_crc_check_history`
    FOREIGN KEY (`checked_out_time`)
    REFERENCES `mydb`.`#__crc_check_history` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`#__crc_tmp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`#__crc_tmp` (
  `path` TEXT NOT NULL,
  `filename` VARCHAR(512) NOT NULL,
  `crc` VARCHAR(32) NOT NULL)
ENGINE = InnoDB;

USE `joomla` ;

-- -----------------------------------------------------
-- Table `joomla`.`tst_user_keys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `joomla`.`tst_user_keys` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(150) NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `series` VARCHAR(191) NOT NULL,
  `invalid` TINYINT(4) NOT NULL,
  `time` VARCHAR(200) NOT NULL,
  `uastring` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `series` (`series` ASC) VISIBLE,
  INDEX `user_id` (`user_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `joomla`.`tst_user_profiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `joomla`.`tst_user_profiles` (
  `user_id` INT(11) NOT NULL,
  `profile_key` VARCHAR(100) NOT NULL,
  `profile_value` TEXT NOT NULL,
  `ordering` INT(11) NOT NULL DEFAULT '0',
  UNIQUE INDEX `idx_user_id_profile_key` (`user_id` ASC, `profile_key` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Simple user profile storage table';


-- -----------------------------------------------------
-- Table `joomla`.`tst_user_usergroup_map`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `joomla`.`tst_user_usergroup_map` (
  `user_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Foreign Key to #__users.id',
  `group_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Foreign Key to #__usergroups.id',
  PRIMARY KEY (`user_id`, `group_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `joomla`.`tst_usergroups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `joomla`.`tst_usergroups` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Primary Key',
  `parent_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Adjacency List Reference Id',
  `lft` INT(11) NOT NULL DEFAULT '0' COMMENT 'Nested set lft.',
  `rgt` INT(11) NOT NULL DEFAULT '0' COMMENT 'Nested set rgt.',
  `title` VARCHAR(100) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idx_usergroup_parent_title_lookup` (`parent_id` ASC, `title` ASC) VISIBLE,
  INDEX `idx_usergroup_title_lookup` (`title` ASC) VISIBLE,
  INDEX `idx_usergroup_adjacency_lookup` (`parent_id` ASC) VISIBLE,
  INDEX `idx_usergroup_nested_set_lookup` USING BTREE (`lft`, `rgt`) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
